version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  build:
    docker:
      - image: "cimg/node:14.15"
    steps:
      - node/install:
          node-version: '14.15'         
      - checkout
      - run:
          name: Fix EB Config Path for Build
          # This is needed because the EB config file is in the root of the project
          # but the build is run from the udagram/udagram-api directory
          command: |
            mkdir -p udagram/udagram-api/.elasticbeanstalk
            cat \<<EOF > udagram/udagram-api/.elasticbeanstalk/config.yml
            branch-defaults:
              master:
                environment: Udagram-final-project-env
            global:
              application_name: udagram-api
              default_platform: node.js
              default_region: us-east-1
              profile: null
              sc: git
            EOF
      # Install dependencies      
      - run:
          name: Install Front-End Dependencies
          command: |
            npm run frontend:install
      - run:
          name: Install API Dependencies
          command: |
            npm run api:install           
      - run:
          name: Front-End Lint
          command: |
            npm run frontend:lint         
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: API Build
          command: |
            npm run api:build

  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: '14.15' 
      - eb/setup
      - aws-cli/setup
      - checkout
      - run:
          name: Create EB Config for Deploy
          # This is needed because the EB config file is in the root of the project
          # but the deploy is run from the udagram/udagram-api directory
          command: |
            mkdir -p udagram/udagram-api/.elasticbeanstalk
            cat \<<EOF > udagram/udagram-api/.elasticbeanstalk/config.yml
            branch-defaults:
              master:
                environment: Udagram-final-project-env
            global:
              application_name: udagram-api
              default_platform: node.js
              default_region: us-east-1
              profile: null
              sc: git
            EOF
      # Deploy app
      - run:
          name: Build and Deploy API
          command: |
            # 1. Prepare the API assets
            npm run api:install
            npm run api:build
            
            # 2. Sync secrets to EB 
            cd udagram/udagram-api
            eb setenv POSTGRES_USERNAME=$POSTGRES_USERNAME \
                      POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
                      POSTGRES_HOST=$POSTGRES_HOST \
                      POSTGRES_DB=$POSTGRES_DB \
                      AWS_BUCKET=$AWS_BUCKET \
                      AWS_REGION=$AWS_REGION \
                      JWT_SECRET=$JWT_SECRET
            
            # 3. Deploy the build
            eb deploy Udagram-final-project-env
      - run:
          name: Build and Deploy Frontend
          command: |
            npm run frontend:install
            npm run frontend:build
            npm run frontend:deploy
            
workflows:
  udagram:
    jobs:
      - build
      # Hold job is used to pause the workflow until the deploy job is approved
      - hold:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold